list = "ABWE SONE VERYLE NGWESEH CHE-C, ENG-B, HBI-C, CSC-C BIMAI ADEL FRANCISCA COM-B, ECO-B, ENG-C, FRE-C, GEO-B, HIS-B, CZE-B AGBOR TOKO ABEN ABI MARTIN COM-C, ECO-B, ENG-C, LIT-C, GEO-C, HIS-B, CZE-C ASUKWA BILLY-CLERGG TAMON BIO-C, ECO-B, ENG-C, GEO-C, HBI-C, MAT-C, REL-C SONA YVONNE LUCY FESE ECO-C, ENG-C, GEO-C, HBI-C, MAT-C, REL-B, CSC-C EDMOND BENEDICT AJAH COM-C, ECO-C, ENG-C, LIT-C, GEO-C, HIS-C, CZE-C AKWA NANCY ANY COM-A, ECO-A, ENG-A, LIT-B, HIS-A, CZE-B EYONG RAMSON BESONG COM-C, ECO-B, ENG-B, GEO-A, HIS-C, CZE-B RAMATOU AMADOU ECO-C, ENG-C, LIT-C, GEO-C, HIS-A, CZE-B KECHA SONITA MBI COM-B, ECO-B, ENG-C, LIT-C, HIS-B, CZE-C MENGOT DAVID AGBOR ECO-C, ENG-B, GEO-C, HIS-B, CZE-B, LOG-C MANTOH EMELINE COM-B, ECO-B, LIT-C, GEO-C, HIS-C, CZE-C TATA ACHILLES TANDZENYUY COM-C, ECO-B, ENG-C, GEO-C, HIS-C, CZE-C NUMFOR BELVINE NDONWI ECO-C, ENG-B, LIT-C, GEO-C, HIS-C, CZE-C NGUEFAC NADIA COM-C, ENG-C, LIT-C, GEO-C, HIS-C, CZE-C TAPONG FRIDEL ENIH COM-C, ECO-C, ENG-A, LIT-C, FRE-C TANLAKA NYUYUMO MBIYDZEKONG ECO-C, ENG-A, GEO-C, HIS-C, CZE-C DORINE TECLAIRE BOUKENGE EYABI COM-B, ENG-B, LIT-C, HIS-C, CZE-C EBUNG JERVIS NZUME ECO-C, ENG-C, GEO-C, HIS-C, REL-B"
// console.log(list)
let regex = /([A-Z]{3}-[A-Z] )/g
let data = (list.match(regex))
// console.log(data);

data.forEach(element => {
    element = element + "|"
    console.log(element)
    
});

